"""add_categories_and_customer_tracking

Revision ID: fefbebdaaffb
Revises: d10d253c5b25
Create Date: 2025-05-29 15:14:26.202997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fefbebdaaffb'
down_revision: Union[str, None] = 'd10d253c5b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('orders', 'wilaya',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'commune',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'delivery_method',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'age')
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'category')
    op.add_column('sales', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('payment_method', sa.Text(), server_default=sa.text("'cash'"), nullable=True))
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'payment_method')
    op.drop_column('sales', 'customer_id')
    op.add_column('products', sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.add_column('orders', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'delivery_method',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('orders', 'commune',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('orders', 'wilaya',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'customer_id')
    op.drop_table('customers')
    op.drop_table('categories')
    # ### end Alembic commands ###
